# Generated by Django 3.0 on 2021-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=20)),
                ('status', models.CharField(default='inactive', max_length=20)),
                ('role', models.CharField(default='user', max_length=30)),
            ],
        ),
    ]
