# Generated by Django 3.2 on 2021-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_pic',
            field=models.FileField(blank=True, default='avtar.png', upload_to='images/'),
        ),
    ]
