# Generated by Django 3.2 on 2021-04-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_artist_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
