# Generated by Django 3.2 on 2021-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_artist_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('event_pic', models.FileField(blank=True, null=True, upload_to='images/')),
                ('address', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.FileField(blank=True, default='avtar.png', null=True, upload_to='images/'),
        ),
    ]
