# Generated by Django 3.2 on 2021-04-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210414_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(blank=True, max_length=600)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
