# Generated by Django 3.2 on 2021-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
