# Generated by Django 3.2 on 2021-04-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210418_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('budget', models.IntegerField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField(max_length=700)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
