# Generated by Django 3.2 on 2021-04-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_bookartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookartist',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.artist'),
        ),
    ]
